version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: server
    ports:
      - ${SERVER_PORT-4000}:${SERVER_PORT-4000}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    environment:
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-database
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  db_data:
  src: